### ISSUE TITLE
API Wallet System Status

### ISSUE THREAD

**Issue by asmodehn** [dvcrn/binance.ex#42]
Hi, I recently found this project, and I am in the process to integrate it into a (very early) project of mine, replacing my hacky binance http client code...

Currently I just miss one API endpoint: https://binance-docs.github.io/apidocs/spot/en/#system-status-system

How would I go about implementing it into binance.ex ?
I'm guessing there are contributing guidelines to follow ?

**Comment by dvcrn** [comment]
Hi! It's really just adding a new method in the main package, adding the necessary structs for the return and adding proper tests. 

This API you mentioned is very simple and straightforward so you should be able to get it up in no time

**Comment by asmodehn** [comment]
Alright then, here it is :-) https://github.com/dvcrn/binance.ex/pull/43

**Comment by asmodehn** [comment]
merged !
