### ISSUE TITLE
Compile -> Runtime Configuration ?

### ISSUE THREAD

**Issue by asmodehn** [dvcrn/binance.ex#44]
Hi everyone, I am opening this issue to start a conversation regarding compiled / runtime configuration.

Few reasons for this : 
- I wanted to test the behaviour of the code when the endpoint is not reachable, with [bypass](https://github.com/PSPDFKit-labs/bypass), but the endpoint is currently set at compile time, and cannot be changed while tests are running.
- I wanted to test authenticated/anonymous requests, but the apikey/secret is currently set at compile time, and, just like the endpoint, cannot be changed at runtime.
- I want to have my apikey/secret in a file in user's home, not in a config.exs (danger of accidental commit). I plan to use [vapor](https://github.com/keathley/vapor) to configure processes on application startup.
- I want to use binance.ex in a multiprocess app...

1. adding a private function to the module where we call `Application.get_env()`, instead of a module tag would make it changeable at runtime. Although not practical it would work fine in monoprocess situations (only one configuration possible) and would allow testing different configurations.

2. _Would be better_: functions need more parameters for tests (or user code) to be able to change endpoint/apikey/secret on call which will make this code usable in a multiprocess situation (one process can connect to one account, another to a different account for instance, they would crash independently, etc.).

Regarding 2., in my specific usecase, I am currently thinking to have one process for public requests, another one for authenticated requests (only this process would be started with apikey and secret). Call rates will be different, public requests can probably be cached for a short time (don't modify the real world), authenticated clients can crash and respawn independently, etc. 

Adding these parameters to functions can make the API more complex, so we should think about how to do this without degrading the dev experience...

I see a couple of options:
- pass a datastructure to all api functions, such as : 
```elixir 
%Binance.Connection{ endpoint: _, apikey: _ , secret: _ }
```
- have an agent holding that "connection" data, configurable at runtime, and providing the same api.
- there are probably other options, but I am not sure which one would be "simple and intuitive enough" for devs here. Python async http clients have "session" concept that may also be useful here: https://docs.aiohttp.org/en/stable/#client-example

What do you think about 1. ? I can do a quick PR, if this is something you are interested in.

What do you think about 2. ?

Also, let me know of any other issue that would be useful that would be useful to work on and fall into this "configuration" topic. I am currently working on this on my code, so I can probably contribute something similar here.

Cheers !

**Comment by asmodehn** [comment]
Regarding this topic, I recently encountered [Krakex](https://github.com/edennis/krakex#usage) which allows passing a `Client` struct to the API functions (see 'Usage' in the README).
This allows using the lib with multiple accounts, changing endpoint in tests, and in general provide more usage flexibility.

**Comment by dvcrn** [comment]
Sorry for not catching this earlier. Was a simple one-line change that's causing this. 

I've changed it to use Application.get_env which means Application.set_env can just change it again. Next step is to pass those in dynamically, but for now this should at least resolve that issue

**Comment by dvcrn** [comment]
https://github.com/dvcrn/binance.ex/releases/tag/v2.0.1
