### ISSUE TITLE
:crypto.hmac/3 removed in OTP 24

### ISSUE THREAD

**Issue by jasbrake** [dvcrn/binance.ex#47]
I'm using Elixir 1.12.0 (compiled with Erlang/OTP 24) and get the following error:

```
(UndefinedFunctionError) function :crypto.hmac/3 is undefined or private
```

According to [https://erlang.org/doc/apps/crypto/new_api.html](https://erlang.org/doc/apps/crypto/new_api.html) `hmac/3` and `hmac/4` have been deprecated in 23.0 and removed in OTP 24.0. The replacement would be `mac/3` or `mac4`.

If it's important to maintain backward compatibility below 22.1 I suspect something like `Kernel.function_exported?(:crypto, :mac, 3)` could be used to determine which function to use (although I have no idea if this is standard practice).

Happy to submit a pull request!

**Comment by dvcrn** [comment]
Currently this plugin is set to Elixir 1.7 and tested through the CI against 1.9.4 with OTP 22.2. 

It could likely be that the newer versions aren't fully compatible yet, so yes we'll need to upgrade and bump the version

**Comment by amacgregor** [comment]
Just submit a PR for this issue https://github.com/dvcrn/binance.ex/pull/48

**Comment by Cinderella-Man** [comment]
Hi @jasbrake,

I'm sorry that this kind of got weird a little bit - please don't feel discouraged by it - I completely missed this issue(sadly not enough time to maintain this lib as well as my other commitments) and would love if you would be the person that would raise PR for this. @amacgregor just jumped on it spontaneously - we should just say "yes" to your initial "Happy to submit a pull request!" a couple of weeks ago.

Apologies

**Comment by jasbrake** [comment]
@Cinderella-Man no worries at all. I was able to downgrade versions and work around it so it wasn't a high priority for me. Also I personally didn't feel comfortable upgrading build versions without a conversation first. My goal was just to see the issue fixed eventually - I'm glad @amacgregor made that happen.
